name: CI-JPandas

on:
  push:
    branches:
      - main
      - fix_ci
      - fix_readme.md
      - feature_creation_et_affichage_dataframe
      - feature_selection_dataframe
      - feature_docker
      - feature_statistiques_dataframe
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Run Tests and Generate JaCoCo Report
        run: mvn clean test jacoco:report

      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco

      - name: Extract JaCoCo Coverage
        id: extract_coverage
        run: |
          mkdir -p badges
          MISSED=$(grep -oPm1 "(?<=missed=\")[0-9]+" target/site/jacoco/jacoco.xml)
          COVERED=$(grep -oPm1 "(?<=covered=\")[0-9]+" target/site/jacoco/jacoco.xml)
          TOTAL=$((MISSED + COVERED))
          PERCENT=$(( 100 * COVERED / TOTAL ))
          echo "Coverage is $PERCENT%"
          echo "::set-output name=coverage::$PERCENT"

          # Générer un badge SVG
          COLOR=red
          if [ $PERCENT -ge 80 ]; then COLOR=green; elif [ $PERCENT -ge 60 ]; then COLOR=yellow; fi
          echo "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"120\" height=\"20\">
            <rect width=\"70\" height=\"20\" fill=\"#555\" />
            <rect x=\"70\" width=\"50\" height=\"20\" fill=\"$COLOR\" />
            <text x=\"10\" y=\"14\" fill=\"#fff\" font-family=\"Verdana\" font-size=\"11\">coverage</text>
            <text x=\"75\" y=\"14\" fill=\"#fff\" font-family=\"Verdana\" font-size=\"11\">$PERCENT%</text>
          </svg>" > badges/coverage.svg

      - name: Upload Badge
        uses: actions/upload-artifact@v4
        with:
          name: coverage-badge
          path: badges/coverage.svg

      - name: Generate Javadoc
        run: mvn javadoc:javadoc

      - name: Upload Javadoc
        uses: actions/upload-artifact@v4
        with:
          name: javadoc
          path: target/site/apidocs

  deploy-javadoc:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up GitHub Token
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          git config --global user.name "LisaZannettacci"
          git config --global user.email "lisa38570@gmail.com"
          git remote set-url origin https://x-access-token:${{ secrets.BOT_TOKEN }}@github.com/LisaZannettacci/JPandas.git

      - name: Download Javadoc Artifact
        uses: actions/download-artifact@v4
        with:
          name: javadoc
          path: site/apidocs

      - name: Download Coverage Badge
        uses: actions/download-artifact@v4
        with:
          name: coverage-badge
          path: site/badges

      - name: Deploy All to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: site
          clean: false
