name: CI-JPandas

on:
  push:
    branches:
      - main
      - fix_ci
      - creation_dataframe
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Run Tests with JaCoCo
        run: mvn verify

      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco

      - name: Generate Javadoc
        run: mvn javadoc:javadoc

      - name: Upload Javadoc
        uses: actions/upload-artifact@v4
        with:
          name: javadoc
          path: target/site/apidocs

  deploy-javadoc:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Empêche de garder les credentials dans le cache pour plus de sécurité

      - name: Set up GitHub Token
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          git config --global user.name "LisaZannettacci"
          git config --global user.email "lisa38570@gmail.com"
          git remote set-url origin https://x-access-token:${{ secrets.BOT_TOKEN }}@github.com/LisaZannettacci/JPandas.git

      - name: Download Javadoc Artifact
        uses: actions/download-artifact@v4
        with:
          name: javadoc
          path: javadoc  # Mettre un dossier temporaire pour éviter des conflits avec `target/site/apidocs`

      - name: Deploy Javadoc to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: javadoc  # Mettre le même dossier que celui défini ci-dessus
